import {query,withTransaction} from './db.mjs';
async function generateUniqueBarcode(c){
  for(let i=0;i<20;i++){
    const body='200'+String(Math.floor(Math.random()*1e9)).padStart(9,'0');
    let sum=0;for(let j=0;j<12;j++){const n=Number(body[j]);sum+=n*(j%2===0?1:3)}
    const barcode=body+String((10-(sum%10))%10);
    const exists=await c.query('SELECT 1 FROM products WHERE barcode=$1 LIMIT 1',[barcode]);
    if(!exists.rows[0])return barcode;
  }
  throw new Error('تعذر إنشاء باركود تلقائي.');
}

export async function listProducts({search='',active=true}={}){const v=[],w=[];if(active!==undefined){v.push(Boolean(active));w.push(`p.active=$${v.length}`)}if(search.trim()){v.push(`%${search.trim()}%`);w.push(`(p.name ILIKE $${v.length} OR COALESCE(p.barcode,'') ILIKE $${v.length})`)}return (await query(`SELECT p.id,p.barcode,p.name,p.category_id,c.name category,p.unit_id,u.name unit,p.purchase_price,p.sale_price,p.current_stock,p.minimum_stock,p.active,p.created_at,p.updated_at FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN units u ON u.id=p.unit_id ${w.length?'WHERE '+w.join(' AND '):''} ORDER BY p.name`,v)).rows;}
export async function getProduct(id){return (await query(`SELECT p.id,p.barcode,p.name,p.category_id,c.name category,p.unit_id,u.name unit,p.purchase_price,p.sale_price,p.current_stock,p.minimum_stock,p.active FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN units u ON u.id=p.unit_id WHERE p.id=$1`,[id])).rows[0]||null;}
export async function createProduct(d,userId){return withTransaction(async c=>{const cat=d.categoryId||(d.category? (await c.query(`SELECT id FROM categories WHERE name=$1 LIMIT 1`,[d.category])).rows[0]?.id:null);const unit=d.unitId||(d.unit? (await c.query(`SELECT id FROM units WHERE name=$1 LIMIT 1`,[d.unit])).rows[0]?.id:null);const barcode=d.barcode||await generateUniqueBarcode(c);const r=await c.query(`INSERT INTO products(barcode,name,category_id,unit_id,purchase_price,sale_price,current_stock,minimum_stock,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,COALESCE($9,true)) RETURNING *`,[barcode,d.name,cat||null,unit||null,Number(d.purchasePrice||0),Number(d.salePrice||0),Number(d.stock||0),Number(d.minimumStock||0),d.active]);if(Number(d.stock||0)!==0)await c.query(`INSERT INTO stock_movements(product_id,type,quantity,note,user_id) VALUES($1,'OPENING',$2,'رصيد افتتاحي',$3)`,[r.rows[0].id,Number(d.stock||0),userId]);return r.rows[0];});}
export async function updateProduct(id,d,userId){return withTransaction(async c=>{const old=await c.query(`SELECT * FROM products WHERE id=$1 FOR UPDATE`,[id]);if(!old.rows[0]){const e=new Error('المنتج غير موجود.');e.statusCode=404;throw e;}const stock=d.stock===undefined?Number(old.rows[0].current_stock):Number(d.stock);const categoryId=d.categoryId??(d.category?(await c.query(`SELECT id FROM categories WHERE name=$1 LIMIT 1`,[d.category])).rows[0]?.id:null);const unitId=d.unitId??(d.unit?(await c.query(`SELECT id FROM units WHERE name=$1 LIMIT 1`,[d.unit])).rows[0]?.id:null);const r=await c.query(`UPDATE products SET barcode=$1,name=$2,category_id=$3,unit_id=$4,purchase_price=$5,sale_price=$6,current_stock=$7,minimum_stock=$8,active=COALESCE($9,active),updated_at=now() WHERE id=$10 RETURNING *`,[d.barcode??old.rows[0].barcode,d.name??old.rows[0].name,categoryId??old.rows[0].category_id,unitId??old.rows[0].unit_id,Number(d.purchasePrice??old.rows[0].purchase_price),Number(d.salePrice??old.rows[0].sale_price),stock,Number(d.minimumStock??old.rows[0].minimum_stock),d.active,id]);const diff=stock-Number(old.rows[0].current_stock);if(diff)await c.query(`INSERT INTO stock_movements(product_id,type,quantity,note,user_id) VALUES($1,$2,$3,'تعديل مباشر للرصيد',$4)`,[id,diff>0?'ADJUSTMENT_IN':'ADJUSTMENT_OUT',diff,userId]);return r.rows[0];});}
export async function deleteProduct(id,userId){return withTransaction(async c=>{const r=await c.query(`SELECT current_stock FROM products WHERE id=$1 FOR UPDATE`,[id]);if(!r.rows[0]){const e=new Error('المنتج غير موجود.');e.statusCode=404;throw e;}await c.query(`UPDATE products SET active=false,updated_at=now() WHERE id=$1`,[id]);return {ok:true};});}
