[CmdletBinding()]
param(
  [string]$DatabaseName = 'bazaar_kolchi',
  [string]$HostName = 'localhost',
  [int]$Port = 5432,
  [string]$DbUser = 'postgres'
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function Write-Step([string]$Message) {
  Write-Host "`n[db:setup] $Message" -ForegroundColor Cyan
}

function Find-Psql {
  $cmd = Get-Command psql.exe -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }

  $roots = @(
    (Join-Path $env:ProgramFiles 'PostgreSQL'),
    (Join-Path ${env:ProgramFiles(x86)} 'PostgreSQL')
  ) | Where-Object { $_ -and (Test-Path $_) }

  foreach ($root in $roots) {
    $candidate = Get-ChildItem $root -Directory -ErrorAction SilentlyContinue |
      Sort-Object Name -Descending |
      ForEach-Object { Join-Path $_.FullName 'bin\psql.exe' } |
      Where-Object { Test-Path $_ } |
      Select-Object -First 1
    if ($candidate) { return $candidate }
  }

  return $null
}

function To-PlainText([Security.SecureString]$SecurePassword) {
  $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecurePassword)
  try {
    return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
  }
  finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
  }
}

function Set-EnvValue([string]$Path, [string]$Key, [string]$Value) {
  $line = "{0}={1}" -f $Key, $Value
  if (Test-Path $Path) {
    $content = Get-Content $Path -Raw
    $pattern = '(?m)^\s*' + [regex]::Escape($Key) + '\s*=.*$'
    if ([regex]::IsMatch($content, $pattern)) {
      $content = [regex]::Replace($content, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $line })
    } else {
      if ($content.Length -gt 0 -and -not $content.EndsWith("`n")) { $content += "`r`n" }
      $content += $line + "`r`n"
    }
    Set-Content -Path $Path -Value $content -Encoding UTF8
  } else {
    @(
      '# Generated by db:setup',
      $line,
      'DB_POOL_MAX=10',
      'PORT=8787',
      'CORS_ORIGIN=http://localhost:5173,null',
      'SESSION_DAYS=30',
      'ADMIN_PASSWORD=' + $AdminPassword,
      'VITE_API_URL=http://localhost:8787/api'
    ) | Set-Content -Path $Path -Encoding UTF8
  }
}

Write-Step 'Checking PostgreSQL service...'
$service = Get-Service -ErrorAction SilentlyContinue |
  Where-Object { $_.Name -like 'postgresql-x64-*' } |
  Sort-Object Name -Descending |
  Select-Object -First 1

if (-not $service) {
  throw 'PostgreSQL Windows service was not found. Install PostgreSQL Server first.'
}

if ($service.Status -ne 'Running') {
  Write-Step "Starting $($service.Name)..."
  Start-Service -Name $service.Name
  $service.WaitForStatus('Running', [TimeSpan]::FromSeconds(20))
}

Write-Step 'Locating psql.exe...'
$psql = Find-Psql
if (-not $psql) {
  throw 'psql.exe was not found. PostgreSQL Command Line Tools must be installed.'
}
Write-Host "[db:setup] psql: $psql"

Write-Step 'Enter the PostgreSQL password for the postgres user.'
$securePassword = Read-Host 'PostgreSQL password' -AsSecureString
$password = To-PlainText $securePassword
if ([string]::IsNullOrWhiteSpace($password)) {
  throw 'PostgreSQL password cannot be empty.'
}

$env:PGPASSWORD = $password
try {
  Write-Step 'Testing PostgreSQL connection...'
  & $psql -h $HostName -p $Port -U $DbUser -d postgres -v ON_ERROR_STOP=1 -tAc 'SELECT 1' | Out-Null
  if ($LASTEXITCODE -ne 0) { throw "PostgreSQL connection failed (exit code $LASTEXITCODE)." }
  Write-Host '[db:setup] PostgreSQL connection OK.' -ForegroundColor Green

  Write-Step "Checking database '$DatabaseName'..."
  $exists = (& $psql -h $HostName -p $Port -U $DbUser -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$DatabaseName'" 2>$null).Trim()
  if ($exists -ne '1') {
    Write-Host "[db:setup] Creating database '$DatabaseName'..."
    & $psql -h $HostName -p $Port -U $DbUser -d postgres -v ON_ERROR_STOP=1 -c "CREATE DATABASE $DatabaseName;"
    if ($LASTEXITCODE -ne 0) { throw "Could not create database '$DatabaseName'." }
  } else {
    Write-Host "[db:setup] Database '$DatabaseName' already exists." -ForegroundColor Green
  }

  $root = Split-Path -Parent $PSScriptRoot
  $envPath = Join-Path $root '.env'

  $AdminPassword = $env:ADMIN_PASSWORD
  if ([string]::IsNullOrWhiteSpace($AdminPassword)) {
    $secure = Read-Host 'Enter ADMIN_PASSWORD (exactly 6 digits)' -AsSecureString
    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try { $AdminPassword = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr) } finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr) }
  }
  if ([string]::IsNullOrWhiteSpace($AdminPassword) -or $AdminPassword.Length -lt 12) { throw 'ADMIN_PASSWORD must be at least 12 characters.' }
  $classes = 0
  if ($AdminPassword -cmatch '[a-z]') { $classes++ }
  if ($AdminPassword -cmatch '[A-Z]') { $classes++ }
  if ($AdminPassword -match '\d') { $classes++ }
  if ($AdminPassword -match '[^A-Za-z0-9]') { $classes++ }
  if ($classes -lt 3) { throw 'ADMIN_PASSWORD must use at least 3 of lowercase/uppercase/digits/symbols.' }
  $encodedPassword = [Uri]::EscapeDataString($password)
  $dbUrl = "postgresql://$DbUser`:$encodedPassword@$HostName`:$Port/$DatabaseName"
  Set-EnvValue -Path $envPath -Key 'DATABASE_URL' -Value $dbUrl
  Set-EnvValue -Path $envPath -Key 'CORS_ORIGIN' -Value 'http://localhost:5173,null'
  Set-EnvValue -Path $envPath -Key 'ADMIN_PASSWORD' -Value $AdminPassword
  Write-Host "[db:setup] Wrote secure API settings to $envPath" -ForegroundColor Green

  Write-Step 'Running database check...'
  Push-Location $root
  try {
    & npm run db:check
    if ($LASTEXITCODE -ne 0) { throw 'db:check failed.' }

    Write-Step 'Running migrations...'
    & npm run db:migrate
    if ($LASTEXITCODE -ne 0) { throw 'db:migrate failed.' }

  }
  finally {
    Pop-Location
  }

  Write-Host "`n[db:setup] PostgreSQL project setup completed successfully." -ForegroundColor Green
  Write-Host "[db:setup] Database: $DatabaseName"
  Write-Host '[db:setup] App login: admin / ADMIN_PASSWORD configured during setup.'
  Write-Host '[db:setup] Next: npm run api   then   npm run desktop:dev'
}
finally {
  Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
  $password = $null
  $securePassword = $null
}
