import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {Bell,CircleHelp,LogOut,Home,ShoppingCart,Settings,Users,Package,Boxes,Warehouse,BarChart3,UserRound,FileText,Cloud,ReceiptText,AlertTriangle,TrendingUp,ChevronLeft,ChevronDown,ChevronUp,CalendarDays,Clock3,RefreshCw,Info,Tags,Ruler,ScanBarcode,ClipboardList,Printer} from "lucide-react";
import "./styles.css";import {subscribeDataChanged,affectsDomains,DATA_DOMAINS,emitDataChanged} from "./data-events.js";import "./topbar-fix.css";import "./dashboard.css";import "./dashboard-five-cards.css";import {api,apiEnabled,logout} from "./api-client.js";import LoginView from "./LoginView.jsx";import "./login.css";import ProductsView from "./ProductsView.jsx";import {CategoriesView,UnitsView} from "./CatalogSettingsView.jsx";import BarcodeView from "./BarcodeView.jsx";import InventoryView from "./InventoryView.jsx";import InventoryMovementsView from "./InventoryMovementsView.jsx";import InventoryHistoryView from "./InventoryHistoryView.jsx";import CustomersView from "./CustomersView.jsx";import ReportsView from "./ReportsView.jsx";import BackupView from "./BackupView.jsx";import SettingsView from "./SettingsView.jsx";import UsersPermissionsView from "./UsersPermissionsView.jsx";import ExpensesView from "./ExpensesView.jsx";import ExcelImportView from "./ExcelImportView.jsx";import SalesView from "./SalesView.jsx";import POSView from "./POSView.jsx";import PrinterManager from "./PrinterManager.jsx";import "./products.css";import "./catalog.css";import "./inventory.css";import "./inventory-movements.css";import "./customers.css";import "./reports.css";import "./backup.css";import "./settings.css";import "./users.css";import "./permissions.css";import "./users-permissions.css";import "./expenses.css";import "./sales.css";import "./responsive-ui.css";
import "./no-visible-scrollbars.css";import "./home-shell.css";
const menu=[{label:"المستخدمون والصلاحيات",key:"users-permissions",Icon:Users},{label:"السلع",key:"products",Icon:Package},{label:"المخزون",key:"inventory",Icon:Warehouse,children:[["حركات المخزون","inventory-movements",ClipboardList]]},{label:"المبيعات",key:"sales",Icon:BarChart3},{label:"المصاريف",key:"expenses",Icon:ReceiptText},{label:"العملاء",key:"customers",Icon:UserRound},{label:"لوحة التحكم",key:"reports",Icon:Home},{label:"الطباعة",key:"print",Icon:Printer},{label:"النسخ الاحتياطي",key:"backup",Icon:Cloud},{label:"الإعدادات العامة",key:"settings",Icon:Settings}];
function Stat({title,value,unit="دج",note,kind,Icon}){const valueText=String(value??"");const valueClass=valueText.length>=11?"statValue statValueLong":valueText.length>=8?"statValue statValueMedium":"statValue";return <article className={`stat ${kind}`}><div className="statIcon"><Icon size={25}/></div><div className="statTitle">{title}</div><div className={valueClass}>{valueText}</div><div className="statUnit">{unit}</div>{note&&<div className="statNote">{note}</div>}</article>}
function Chart({daily=[]}){const rows=daily.slice(-7);const values=rows.map(x=>Number(x.total||0));const max=Math.max(...values,1);const pts=rows.map((item,i)=>[45+(i*(528/Math.max(rows.length-1,1))),180-(values[i]/max)*135]);const line=pts.map(([x,y],i)=>`${i?'L':'M'} ${x.toFixed(1)} ${y.toFixed(1)}`).join(' ');const total=values.reduce((a,b)=>a+b,0);return <section className="panel chartPanel"><div className="panelHead"><div><h2>المبيعات خلال 7 أيام</h2><div className="legend"><i/> المبيعات (دج)</div></div></div><div className="chart"><div className="axis">{['14K','12K','10K','8K','6K','4K','2K','0'].map(x=><span key={x}>{x}</span>)}</div>{rows.length?<svg viewBox="0 0 620 215" preserveAspectRatio="none">{[30,52,74,96,118,140,162,184].map(y=><line key={y} x1="40" x2="610" y1={y} y2={y} className="grid"/>)}<path d={`${line} L ${pts[pts.length-1][0]} 190 L ${pts[0][0]} 190 Z`} className="area"/><path d={line} className="line"/>{pts.map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="5"/><text x={x} y={y-12} textAnchor="middle">{values[i].toLocaleString('en-US',{useGrouping:false})}</text><text x={x} y="210" textAnchor="middle" className="day">{new Date(rows[i].day||rows[i].sale_day).toLocaleDateString('ar-DZ',{weekday:'short'})}</text></g>)}</svg>:<div className="emptyReport">لا توجد مبيعات في آخر 7 أيام.</div>}</div><div className="chartFoot"><span>من PostgreSQL</span><strong>إجمالي المبيعات: <b>{total.toLocaleString('en-US',{minimumFractionDigits:2,useGrouping:false})} دج</b></strong></div></section>}
function Operations({items=[]}){return <section className="panel ops"><div className="panelHead"><h2>آخر العمليات</h2></div>{items.length?items.map(item=><div className="operation" key={item.id||item.invoice}><div className="opIcon"><ShoppingCart size={19}/></div><div><strong>عملية بيع</strong><small>فاتورة {item.invoice}</small></div><b>{Number(item.amount||0).toFixed(2)} دج</b><span>{new Date(item.createdAt).toLocaleString('ar-DZ')} ◷</span></div>):<div className="emptyReport">لا توجد عمليات بيع.</div>}</section>}
function Dashboard(){const[remote,setRemote]=useState(null);const reload=React.useCallback(()=>{api(`/reports/dashboard?from=${encodeURIComponent(new Date(new Date().setHours(0,0,0,0)).toISOString())}`).then(setRemote).catch(()=>setRemote(null));},[]);useEffect(()=>{reload();const off=subscribeDataChanged((event)=>{if(affectsDomains(event,[DATA_DOMAINS.SALES,DATA_DOMAINS.CASH,DATA_DOMAINS.INVENTORY,DATA_DOMAINS.CUSTOMERS,DATA_DOMAINS.EXPENSES,DATA_DOMAINS.REPORTS]))reload();});return()=>off?.();},[reload]);const inventoryValue=Number(remote?.inventoryValue||0);const lowStockCount=Number(remote?.low||0);const salesTotal=Number(remote?.sales?.total||0);const salesCount=Number(remote?.sales?.count||0);const profit=Number(remote?.netProfit??remote?.profit??0);const s={todaySales:salesTotal,salesCount,todayProfit:profit,inventoryValue,lowStockCount};return <><section className="statsRow"><Stat title="مبيعات اليوم" value={s.todaySales.toLocaleString('en-US',{minimumFractionDigits:2,useGrouping:false})} note="من قاعدة البيانات" kind="green" Icon={ShoppingCart}/><Stat title="ربح اليوم" value={s.todayProfit.toLocaleString('en-US',{minimumFractionDigits:2,useGrouping:false})} note="بعد المصاريف والمرتجعات" kind="purple" Icon={TrendingUp}/><Stat title="عدد عمليات البيع" value={s.salesCount} unit="عملية" note="من PostgreSQL" kind="blue" Icon={ShoppingCart}/><Stat title="متوسط قيمة البيع" value={(s.salesCount?s.todaySales/s.salesCount:0).toLocaleString('en-US',{minimumFractionDigits:2,useGrouping:false})} note="لكل عملية بيع" kind="blue" Icon={ReceiptText}/><article className="stat warning"><div className="statIcon"><AlertTriangle/></div><div className="statTitle">سلع منخفضة المخزون</div><div className="statValue">{s.lowStockCount}</div><div className="statUnit">سلع</div><button className="link">عرض السلع <ChevronLeft size={15}/></button></article></section><section className="mainGrid"><Operations items={remote?.operations||[]}/><Chart daily={remote?.daily||[]}/></section><section className="bottom"><article className="notice stock"><div className="noticeIcon"><Bell/></div><div><h3>تنبيهات المخزون</h3><strong>{s.lowStockCount} سلع منخفضة المخزون</strong><p>يجب إعادة الطلب لتجنب نفاد المخزون</p></div><button>عرض السلع <ChevronLeft size={15}/></button></article><article className="notice tip"><div className="noticeIcon"><BarChart3/></div><div><h3>نصيحة اليوم</h3><p>تعتمد الأرقام عند تفعيل PostgreSQL على البيانات الحقيقية.</p></div><Info/></article></section></>}
function Placeholder({title}){return <div className="title"><h1>{title}</h1><p>سيتم بناء هذا القسم في المرحلة التالية.</p></div>}
function openPOS(){const url=new URL(window.location.href);url.searchParams.set("pos","1");url.searchParams.delete("edit");const w=window.open(url.toString(),"bazaar-pos","fullscreen=yes,resizable=yes,scrollbars=no");if(w)w.focus()}
function HomeCard({label,Icon,onClick,accent=false,description}){return <button type="button" className={`homeCard${accent?' homeCardAccent':''}`} onClick={onClick}><span className="homeCardIcon"><Icon size={28}/></span><span className="homeCardText"><strong>{label}</strong>{description&&<small>{description}</small>}</span><span className="homeCardWatermark"><Icon size={68}/></span><span className="homeCardArrow"><ChevronLeft size={18}/></span></button>}
function renderView(view){switch(view){case"dashboard":return <Dashboard/>;case"products":return <ProductsView/>;case"add-product":return <ProductsView autoOpen/>;case"categories":return <CategoriesView/>;case"units":return <UnitsView/>;case"barcode":return <BarcodeView/>;case"excel-import":return <ExcelImportView/>;case"inventory":return <InventoryView/>;case"inventory-movements":return <InventoryMovementsView/>;case"inventory-history":return <InventoryHistoryView/>;case"sales":return <SalesView/>;case"customers":return <CustomersView/>;case"reports":return <ReportsView/>;case"print":return <PrinterManager/>;case"backup":return <BackupView/>;case"settings":return <SettingsView/>;case"users-permissions":return <UsersPermissionsView/>;case"expenses":return <ExpensesView/>;default:return <Placeholder title={menu.find(x=>x.key===view)?.label||"القسم"}/>}}
function HomeStatus(){const[now,setNow]=useState(new Date());useEffect(()=>{const id=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(id)},[]);const online=typeof navigator==="undefined"?true:navigator.onLine;return <div className="homeStatus"><article className="homeStatusCard"><span className="homeStatusIcon homeStatusPurple"><Clock3 size={24}/></span><span><small>الوقت</small><strong className="homeClock">{now.toLocaleTimeString("ar-DZ",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false})}</strong></span></article><article className="homeStatusCard"><span className="homeStatusIcon homeStatusBlue"><CalendarDays size={24}/></span><span><small>التاريخ</small><strong>{now.toLocaleDateString("ar-DZ",{day:"2-digit",month:"long",year:"numeric"})}</strong></span></article><article className="homeStatusCard"><span className="homeStatusIcon homeStatusBlue"><RefreshCw size={24}/></span><span><small>آخر مزامنة</small><strong>متزامن الآن</strong></span></article><article className="homeStatusCard"><span className="homeStatusIcon homeStatusGreen"><span className="homePulse"/><RefreshCw size={24}/></span><span><small>حالة النظام</small><strong className={online?"online":"offline"}>{online?"متصل":"غير متصل"}</strong></span></article></div>}
function App(){
  useEffect(()=>{
    try{
      const t=localStorage.getItem('bazaar_api_token');
      if(t)window.desktopAPI?.setAuthToken?.(t);
    }catch{}
  },[]);
  if(new URLSearchParams(window.location.search).get("pos")==="1")return <POSView/>;
  const[view,setView]=useState(null),[auth,setAuth]=useState(()=>Boolean(localStorage.getItem("bazaar_api_token")));
  useEffect(()=>{
    const handler=e=>{const key=e?.detail?.key;if(key)setView(key)};
    const authExpired=()=>{
      setAuth(false);
      setView(null);
    };
    window.addEventListener("app:navigate",handler);
    window.addEventListener("auth:expired",authExpired);
    return()=>{
      window.removeEventListener("app:navigate",handler);
      window.removeEventListener("auth:expired",authExpired);
    };
  },[]);
  if(apiEnabled()&&!auth)return <LoginView onSuccess={()=>setAuth(true)}/>;const go=key=>setView(key);const homeCards=[{label:"نقطة البيع",key:"pos",Icon:ShoppingCart,description:"إتمام عمليات البيع"},{label:"السلع",key:"products",Icon:Package,description:"المنتجات والتصنيفات"},{label:"المخزون",key:"inventory",Icon:Warehouse,description:"المخزون والحركات"},{label:"المبيعات",key:"sales",Icon:BarChart3,description:"الفواتير والمبيعات"},{label:"العملاء",key:"customers",Icon:UserRound,description:"العملاء والديون"},{label:"المصاريف",key:"expenses",Icon:ReceiptText,description:"المصاريف"},{label:"لوحة التحكم",key:"reports",Icon:Home,description:"الإحصائيات والتحليل والتقارير"},{label:"الطباعة",key:"print",Icon:Printer,description:"الطابعات والإعدادات"},{label:"النسخ الاحتياطي",key:"backup",Icon:Cloud,description:"نسخ واستعادة"},{label:"المستخدمون والصلاحيات",key:"users-permissions",Icon:Users,description:"إدارة المستخدمين والأدوار والصلاحيات"},{label:"الإعدادات العامة",key:"settings",Icon:Settings,description:"إعدادات النظام"}];return <div className="homeShell">{view===null?<main className="homeStage"><div className="homeHero"><HomeStatus/><div className="homeHeroGreeting"><div className="homeGreeting">بسم الله، توكلت على الله، ولا حول ولا قوة إلا بالله</div><div className="homeGreetingMark"><span></span><i></i></div></div></div><div className="homeGrid">{homeCards.map(card=><HomeCard key={card.key} {...card} accent={card.key==="pos"} onClick={card.key==="pos"?openPOS:()=>go(card.key)}/>)}</div></main>:<main className="fullViewStage"><div className="fullViewHeader"><button type="button" className="backHome" onClick={()=>setView(view==="inventory-movements"||view==="inventory-history"?"inventory":null)}><ChevronLeft size={20}/> رجوع</button><div className="fullViewTitle"><strong>{(menu.find(x=>x.key===view)?.label)||(view==="inventory-movements"?"حركات المخزون":view==="inventory-history"?"سجل حركات المخزون":"القسم")}</strong><span>كل شيء بالمعقول</span></div></div><div className="fullViewBody">{renderView(view)}</div></main>}</div>}
createRoot(document.getElementById("root")).render(<App/>);
import("./barcode-input-fix.js");
