import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { Bell, CircleHelp, LogOut, ShoppingCart, Settings, Home, Store, Users, ShieldCheck, Package, Boxes, Warehouse, BarChart3, UserRound, FileText, Cloud, ReceiptText, WalletCards, AlertTriangle, TrendingUp, ChevronLeft, ChevronDown, ChevronUp, CalendarDays, Info, Tags, Ruler, ScanBarcode, ClipboardList } from "lucide-react";
import "./styles.css";
import "./dashboard.css";
import { dashboardData } from "./dashboard-data.js";
import { loadProducts } from "./products-data.js";
import ProductsView from "./ProductsView.jsx";
import { CategoriesView, UnitsView } from "./CatalogSettingsView.jsx";
import BarcodeView from "./BarcodeView.jsx";
import InventoryView from "./InventoryView.jsx";
import InventoryMovementsView from "./InventoryMovementsView.jsx";
import "./products.css";
import "./catalog.css";
import "./inventory.css";
import "./inventory-movements.css";

const menu=[{label:"نظرة عامة",key:"dashboard",Icon:Home},{label:"المتجر",key:"store",Icon:Store},{label:"المستخدمون",key:"users",Icon:Users},{label:"الصلاحيات",key:"permissions",Icon:ShieldCheck},{label:"السلع",key:"products",Icon:Package,children:[["قائمة السلع","products",Package],["إضافة سلعة","add-product",Boxes],["تصنيفات السلع","categories",Tags],["الوحدات","units",Ruler],["الباركود","barcode",ScanBarcode]]},{label:"المخزون",key:"inventory",Icon:Warehouse,children:[["نظرة عامة على المخزون","inventory",Warehouse],["حركات المخزون","inventory-movements",ClipboardList]]},{label:"المبيعات",key:"sales",Icon:BarChart3},{label:"العملاء",key:"customers",Icon:UserRound},{label:"التقارير",key:"reports",Icon:FileText},{label:"النسخ الاحتياطي",key:"backup",Icon:Cloud},{label:"الإعدادات العامة",key:"settings",Icon:Settings}];
function Stat({title,value,unit="دج",note,kind,Icon}){return <article className={`stat ${kind}`}><div className="statIcon"><Icon size={25}/></div><div className="statTitle">{title}</div><div className="statValue">{value}</div><div className="statUnit">{unit}</div>{note&&<div className="statNote">{note}</div>}</article>}
function Chart(){const max=Math.max(...dashboardData.sales.map(x=>x.value)),pts=dashboardData.sales.map((item,i)=>[45+i*88,180-(item.value/max)*135]),line=pts.map(([x,y],i)=>`${i?'L':'M'} ${x} ${y}`).join(' ');return <section className="panel chartPanel"><div className="panelHead"><div><h2>المبيعات خلال 7 أيام</h2><div className="legend"><i/> المبيعات (دج)</div></div><button className="range"><ChevronDown size={15}/> 7 أيام <CalendarDays size={15}/></button></div><div className="chart"><div className="axis">{['14K','12K','10K','8K','6K','4K','2K','0'].map(x=><span key={x}>{x}</span>)}</div><svg viewBox="0 0 620 215" preserveAspectRatio="none">{[30,52,74,96,118,140,162,184].map(y=><line key={y} x1="40" x2="610" y1={y} y2={y} className="grid"/>)}<path d={`${line} L 573 190 L 45 190 Z`} className="area"/><path d={line} className="line"/>{pts.map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="5"/><text x={x} y={y-12} textAnchor="middle">{dashboardData.sales[i].value.toLocaleString()}</text><text x={x} y="210" textAnchor="middle" className="day">{dashboardData.sales[i].day}</text></g>)}</svg></div><div className="chartFoot"><span>↗ +16% عن الفترة السابقة</span><strong>إجمالي المبيعات خلال 7 أيام: <b>{dashboardData.sales.reduce((sum,x)=>sum+x.value,0).toLocaleString('en-US',{minimumFractionDigits:2})} دج</b></strong></div></section>}
function Operations(){return <section className="panel ops"><div className="panelHead"><h2>آخر العمليات</h2><button className="textBtn">عرض الكل <ChevronLeft size={15}/></button></div>{dashboardData.operations.map(item=><div className="operation" key={item.invoice}><div className="opIcon"><ShoppingCart size={19}/></div><div><strong>عملية بيع</strong><small>فاتورة {item.invoice}</small></div><b>{item.amount.toFixed(2)} دج</b><span>{item.time} ◷</span></div>)}</section>}
function Dashboard(){const products=loadProducts();const inventoryValue=products.reduce((sum,p)=>sum+(Number(p.stock)||0)*(Number(p.purchase)||0),0);const lowStockCount=products.filter(p=>Number(p.stock)>0&&Number(p.stock)<=Number(p.min)).length;const s={...dashboardData.stats,inventoryValue,lowStockCount};return <><div className="title"><div><h1>نظرة عامة <TrendingUp/></h1><p>الإعدادات <ChevronLeft/> نظرة عامة</p></div></div><section className="grid four"><Stat title="مبيعات اليوم" value={s.todaySales.toLocaleString('en-US',{minimumFractionDigits:2})} note="↗ +18% عن أمس" kind="green" Icon={ShoppingCart}/><Stat title="ربح اليوم" value={s.todayProfit.toLocaleString('en-US',{minimumFractionDigits:2})} note="↗ +15% عن أمس" kind="purple" Icon={TrendingUp}/><Stat title="عدد عمليات البيع" value={s.salesCount} unit="عملية" note="↗ +8 عن أمس" kind="blue" Icon={ShoppingCart}/><Stat title="قيمة المخزون" value={s.inventoryValue.toLocaleString('en-US',{minimumFractionDigits:2})} note="إجمالي قيمة السلع" kind="orange" Icon={Boxes}/></section><section className="grid three second"><Stat title="متوسط قيمة البيع" value={s.averageSale.toLocaleString('en-US',{minimumFractionDigits:2})} note="لكل عملية بيع" kind="blue" Icon={ReceiptText}/><Stat title="المبلغ الموجود في الصندوق" value={s.cashBalance.toLocaleString('en-US',{minimumFractionDigits:2})} note="⟳ آخر تحديث: الآن" kind="teal" Icon={WalletCards}/><article className="stat warning"><div className="statIcon"><AlertTriangle/></div><div className="statTitle">سلع منخفضة المخزون</div><div className="statValue">{s.lowStockCount}</div><div className="statUnit">سلع</div><button className="link">عرض السلع <ChevronLeft size={15}/></button></article></section><section className="mainGrid"><Operations/><Chart/></section><section className="bottom"><article className="notice stock"><div className="noticeIcon"><Bell/></div><div><h3>تنبيهات المخزون</h3><strong>{s.lowStockCount} سلع منخفضة المخزون</strong><p>يجب إعادة الطلب لتجنب نفاد المخزون</p></div><button>عرض السلع <ChevronLeft size={15}/></button></article><article className="notice tip"><div className="noticeIcon"><BarChart3/></div><div><h3>نصيحة اليوم</h3><p>مبيعاتك اليوم أعلى من أمس بنسبة <strong>18%</strong><br/>استمر على هذا الأداء الرائع!</p></div><Info/></article></section></>}
function Placeholder({title}){return <div className="title"><h1>{title}</h1><p>سيتم بناء هذا القسم في المرحلة التالية.</p></div>}
function App(){const[mobile,setMobile]=useState(false),[productsOpen,setProductsOpen]=useState(true),[inventoryOpen,setInventoryOpen]=useState(true),[notifications,setNotifications]=useState(3),[view,setView]=useState("dashboard");const go=key=>{setView(key);if(["products","add-product","categories","units","barcode"].includes(key))setProductsOpen(true);if(["inventory","inventory-movements"].includes(key))setInventoryOpen(true)};return <div className="app"><header className="top"><div className="brand"><div className="brandLogo">▰</div><div><strong>كل شيء بالمعقول</strong><small>نقطة بيع</small></div></div><div className="topCenter"><button className="other"><ShoppingCart/> سلة أخرى</button><button className="pos"><ShoppingCart/> نقطة البيع</button></div><div className="tools"><button onClick={()=>setNotifications(0)}><Bell/><em>{notifications}</em> إشعارات</button><button><CircleHelp/> مساعدة</button><button><LogOut/> خروج</button></div><button className="mobile" onClick={()=>setMobile(!mobile)} aria-label="فتح القائمة">☰</button></header><aside className={mobile?'side open':'side'}><div className="sideTitle"><Settings/> الإعدادات</div>{menu.map(({label,key,Icon,children})=><div key={label}><button className={view===key?'nav active':'nav'} onClick={()=>children?(key==='products'?setProductsOpen(!productsOpen):setInventoryOpen(!inventoryOpen)):go(key)}><Icon/><span>{label}</span>{children&&((key==='products'?productsOpen:inventoryOpen)?<ChevronUp className="navArrow"/>:<ChevronDown className="navArrow"/>)}</button>{children&&((key==='products'?productsOpen:inventoryOpen))&&<div className="sub">{children.map(([child,childKey,ChildIcon])=><button className={view===childKey?'selectedSub':''} key={child} onClick={()=>go(childKey)}><ChildIcon size={15}/><span>{child}</span></button>)}</div>}</div>)}</aside><main className="content">{view==='dashboard'&&<Dashboard/>}{view==='products'&&<ProductsView/>}{view==='add-product'&&<ProductsView autoOpen/>}{view==='categories'&&<CategoriesView/>}{view==='units'&&<UnitsView/>}{view==='barcode'&&<BarcodeView/>}{view==='inventory'&&<InventoryView/>}{view==='inventory-movements'&&<InventoryMovementsView/>}{!['dashboard','products','add-product','categories','units','barcode','inventory','inventory-movements'].includes(view)&&<Placeholder title={menu.find(x=>x.key===view)?.label||'القسم'}/>}</main></div>}
createRoot(document.getElementById("root")).render(<App/>);
