const FAVORITES_KEY="bazaar-pos-favorites";
const qs=(s,r=document)=>r.querySelector(s);
const qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const readFavorites=()=>{try{const v=JSON.parse(localStorage.getItem(FAVORITES_KEY)||"[]");return Array.isArray(v)?v.map(String):[]}catch{return[]}};
const writeFavorites=v=>localStorage.setItem(FAVORITES_KEY,JSON.stringify(v.map(String)));
const productData=b=>({name:qs("strong",b)?.textContent?.trim()||"سلعة",barcode:qs("small",b)?.textContent?.trim()||"",price:qs("span",b)?.textContent?.trim()||"",stock:qs("em",b)?.textContent?.trim()||""});

function injectStyles(){if(qs("#bazaar-pos-products-style"))return;const s=document.createElement("style");s.id="bazaar-pos-products-style";s.textContent=`
.posView .productResults{display:none!important;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:8px;width:100%;margin:0 0 10px;padding:0;box-sizing:border-box;direction:rtl}
.posView .productResults.posResultsVisible{display:grid!important}
.posView .posProduct{min-width:0;min-height:70px;padding:8px 10px;border:1px solid #dce4ef;border-radius:9px;background:#fff;color:#17233a;font-family:inherit;text-align:right;cursor:pointer;display:grid;grid-template-columns:minmax(0,1fr) auto;grid-template-rows:auto auto auto;gap:2px 8px;box-sizing:border-box}
.posView .posProduct:hover:not(:disabled){border-color:#7da7e8;box-shadow:0 4px 12px rgba(16,35,61,.08)}
.posView .posProduct:disabled{opacity:.5;cursor:not-allowed}.posView .posProduct strong{grid-column:1/-1;font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.posView .posProduct small{grid-column:1;font-size:10px;color:#7b8798;direction:ltr;text-align:right;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.posView .posProduct span{grid-column:2;grid-row:2/4;align-self:center;color:#145fd5;font-size:14px;font-weight:800;white-space:nowrap}.posView .posProduct em{grid-column:1;font-size:10px;color:#16845f;font-style:normal;white-space:nowrap}
.posView .posFavorites{display:none;width:100%;margin:8px 0 10px;padding:8px;box-sizing:border-box;background:#fff;border:1px solid #dfe6f0;border-radius:9px;direction:rtl}.posView .posFavoritesHeader{height:28px;display:flex;align-items:center;justify-content:space-between;padding:0 3px 6px;margin-bottom:7px;border-bottom:1px solid #edf1f6}.posView .posFavoritesHeader strong{font-size:14px;color:#17233a}.posView .posFavoritesHeader small{margin-right:8px;color:#7b8798;font-size:10px}.posView .posFavoritesHeader span{color:#ed1b68}.posView .posFavoritesGrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:7px}.posView .posFavoriteCard{position:relative;min-width:0}.posView .posFavoriteMain{width:100%;min-height:52px;padding:6px 29px 6px 8px;border:1px solid #e0e6ef;border-radius:7px;background:#fbfcff;color:#17233a;font-family:inherit;text-align:right;cursor:pointer;display:grid;grid-template-columns:minmax(0,1fr) auto;grid-template-rows:auto auto;gap:2px 7px;box-sizing:border-box}.posView .posFavoriteMain strong{grid-column:1/-1;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.posView .posFavoriteMain small{font-size:9px;color:#7b8798;direction:ltr}.posView .posFavoriteMain b{font-size:12px;color:#145fd5}.posView .posFavoriteStar{position:absolute;top:17px;right:7px;width:17px;height:17px;padding:0;border:0;background:transparent;color:#ed1b68;cursor:pointer;z-index:2}
@media(max-width:900px){.posView .productResults,.posView .posFavoritesGrid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.posView .productResults,.posView .posFavoritesGrid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}

function renderFavorites(box,buttons){let fav=readFavorites();const products=buttons.map(productData).filter(p=>p.barcode);if(!fav.length&&products.length){fav=products.slice(0,6).map(p=>p.barcode);writeFavorites(fav)}const selected=buttons.filter(b=>fav.includes(productData(b).barcode));box.innerHTML=`<div class="posFavoritesHeader"><div><strong>المفضلة</strong><small>إضافة سريعة للسلة</small></div><span>★</span></div>`;const grid=document.createElement("div");grid.className="posFavoritesGrid";selected.forEach(original=>{const p=productData(original),card=document.createElement("div"),main=document.createElement("button"),star=document.createElement("button");card.className="posFavoriteCard";main.type="button";main.className="posFavoriteMain";main.innerHTML="<strong></strong><small></small><b></b>";qs("strong",main).textContent=p.name;qs("small",main).textContent=p.barcode;qs("b",main).textContent=p.price;main.onclick=()=>original.click();star.type="button";star.className="posFavoriteStar";star.textContent="★";star.title="إزالة من المفضلة";star.onclick=e=>{e.stopPropagation();writeFavorites(readFavorites().filter(x=>x!==String(p.barcode)));render()};card.append(main,star);grid.appendChild(card)});if(!selected.length){const e=document.createElement("div");e.textContent="لا توجد سلع مفضلة حاليًا";e.style.cssText="grid-column:1/-1;text-align:center;color:#98a2b3;padding:8px;font-size:12px";grid.appendChild(e)}box.appendChild(grid);box.style.setProperty("display","block","important")}

function render(){const pos=qs(".posView");if(!pos)return;injectStyles();const results=qs(".productResults",pos),search=qs(".posSearch input",pos),cart=qs(".cartTable",pos);if(!results||!search||!cart)return;const buttons=qsa(".posProduct",results),query=String(search.value||"").trim();let fav=qs(".posFavorites",pos);if(!fav){fav=document.createElement("section");fav.className="posFavorites";cart.parentNode.insertBefore(fav,cart)}if(query){results.classList.add("posResultsVisible");fav.style.setProperty("display","none","important");return}results.classList.remove("posResultsVisible");results.style.setProperty("display","none","important");renderFavorites(fav,buttons)}

let frame=0;const schedule=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(render)};window.addEventListener("input",e=>{if(e.target?.matches?.(".posSearch input"))schedule()});new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener("load",schedule);setTimeout(schedule,250);

function ensureCloseRail(){if(qs(".posSideRail"))return;const rail=document.createElement("aside");rail.className="posSideRail";rail.innerHTML='<button type="button" class="posSideRailTab">☰</button><div class="posSideRailPanel"><div class="posSideRailTitle">نقطة البيع</div><button type="button" class="posRailPrintButton">طباعة الوصل</button><button type="button" class="posCloseButton">إغلاق نقطة البيع</button></div>';document.body.appendChild(rail);qs(".posSideRailTab",rail).onclick=()=>rail.classList.toggle("open");qs(".posCloseButton",rail).onclick=()=>window.close();document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!qs(".barcodeOverlay")&&!qs(".invoiceOverlay"))rail.classList.remove("open")})}
const observer=new MutationObserver(()=>{if(qs(".posView"))ensureCloseRail()});observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener("load",ensureCloseRail);setTimeout(ensureCloseRail,300);
