const FAVORITES_KEY="bazaar-pos-favorites";
const PRODUCTS_KEY="bazaar-kolchi-products";
const qs=(s,r=document)=>r.querySelector(s);
const qsa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const readFavorites=()=>{try{const v=JSON.parse(localStorage.getItem(FAVORITES_KEY)||"[]");return Array.isArray(v)?v.map(String):[]}catch{return[]}};
const writeFavorites=v=>localStorage.setItem(FAVORITES_KEY,JSON.stringify(v.map(String)));
const textOf=(el,sel)=>qs(sel,el)?.textContent?.trim()||"";
const productData=b=>({name:textOf(b,"strong")||"سلعة",barcode:textOf(b,"small"),price:textOf(b,"span")||textOf(b,"b")});
function install(){if(qs("#bazaar-pos-safe-fix"))return;const style=document.createElement("style");style.id="bazaar-pos-safe-fix";style.textContent=`
.posView .productResults{display:none!important;width:100%;box-sizing:border-box;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:6px;margin:0 0 8px;padding:0;direction:rtl}.posView .productResults.posResultsVisible{display:grid!important}.posView .posProduct{display:flex!important;align-items:center;justify-content:space-between;gap:8px;min-width:0;height:42px;min-height:42px;padding:4px 9px;border:1px solid #dce4ef;border-radius:7px;background:#fff;font-family:inherit;cursor:pointer;box-sizing:border-box}.posView .posProduct strong{font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;min-width:0;flex:1}.posView .posProduct small,.posView .posProduct em{display:none!important}.posView .posProduct span{font-size:11px;color:#145fd5;font-weight:800;white-space:nowrap}.posView .posFavorites{display:block!important;width:100%;margin-top:10px;padding:7px;box-sizing:border-box;background:#fff;border:1px solid #dfe6f0;border-radius:8px;direction:rtl}.posView .posFavoritesHeader{height:24px;display:flex;align-items:center;justify-content:space-between;padding:0 3px 5px;margin-bottom:6px;border-bottom:1px solid #edf1f6}.posView .posFavoritesHeader strong{font-size:13px;color:#17233a}.posView .posFavoritesHeader span{color:#ed1b68}.posView .posFavoritesGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:5px}.posView .posFavoriteCard{position:relative;min-width:0}.posView .posFavoriteMain{width:100%;height:38px;min-height:38px;padding:4px 25px 4px 7px;border:1px solid #e0e6ef;border-radius:6px;background:#fbfcff;color:#17233a;font-family:inherit;text-align:right;cursor:pointer;display:flex;align-items:center;justify-content:space-between;gap:6px;box-sizing:border-box}.posView .posFavoriteMain strong{font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;flex:1;min-width:0}.posView .posFavoriteMain small{display:none}.posView .posFavoriteMain b{font-size:11px;color:#145fd5;white-space:nowrap}.posView .posFavoriteStar{position:absolute;top:10px;right:5px;width:15px;height:15px;padding:0;border:0;background:transparent;color:#ed1b68;cursor:pointer;z-index:2}.posView .paymentPanel .posFavorites{margin-bottom:0}.posView .payLine strong{display:block!important;visibility:visible!important;opacity:1!important;font-size:28px!important;color:#125ad0!important}.posView .basicSale strong{display:block!important;visibility:visible!important;opacity:1!important}@media(max-width:900px){.posView .productResults{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.posView .productResults{grid-template-columns:1fr}.posView .posFavoritesGrid{grid-template-columns:repeat(3,minmax(0,1fr))}}
`;document.head.appendChild(style)}
function price(value){const raw=String(value??"").replace(/\s*دج\s*$/u,"").replace(/,/g,"").trim();const n=Number(raw);return Number.isFinite(n)?`${n.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})} دج`:value}
function renderFavorites(payment,buttons){let box=qs(".posFavorites",payment);if(!box){box=document.createElement("section");box.className="posFavorites";payment.appendChild(box)}const available=buttons.map(b=>({button:b,data:productData(b)})).filter(x=>x.data.barcode);let fav=readFavorites();if(!fav.length&&available.length){fav=available.slice(0,6).map(x=>x.data.barcode);writeFavorites(fav)}const selected=available.filter(x=>fav.includes(String(x.data.barcode)));box.innerHTML=`<div class="posFavoritesHeader"><strong>المفضلة</strong><span>★</span></div><div class="posFavoritesGrid"></div>`;const grid=qs(".posFavoritesGrid",box);selected.forEach(({button,data})=>{const card=document.createElement("div");card.className="posFavoriteCard";const main=document.createElement("button");main.type="button";main.className="posFavoriteMain";main.innerHTML=`<strong>${data.name}</strong><b>${price(data.price)}</b>`;main.onclick=e=>{e.preventDefault();e.stopPropagation();button.click()};const star=document.createElement("button");star.type="button";star.className="posFavoriteStar";star.textContent="★";star.title="إزالة من المفضلة";star.onclick=e=>{e.preventDefault();e.stopPropagation();writeFavorites(readFavorites().filter(x=>x!==String(data.barcode)));schedule()};card.append(main,star);grid.append(card)})}
function render(){const pos=qs(".posView");if(!pos)return;install();const results=qs(".productResults",pos),search=qs(".posSearch input",pos),payment=qs(".paymentPanel",pos);if(!results||!search||!payment)return;const query=String(search.value||"").trim();const buttons=qsa("button",results);buttons.forEach(b=>b.classList.add("posProduct"));results.classList.toggle("posResultsVisible",!!query);results.style.setProperty("display",query?"grid":"none","important");let box=qs(".posFavorites",pos);if(box&&box.parentNode!==payment)payment.appendChild(box);renderFavorites(payment,buttons);if(box)box.style.setProperty("display","block","important");qsa(".posProduct span,.posFavoriteMain b,.cartRow > span:nth-child(3),.cartRow > strong,.payLine strong,.basicSale strong",pos).forEach(el=>{if(/دج/u.test(el.textContent||""))el.textContent=price(el.textContent)})}
let raf=0;function schedule(){cancelAnimationFrame(raf);raf=requestAnimationFrame(render)}
install();document.addEventListener("input",e=>{if(e.target?.matches?.(".posSearch input"))schedule()},true);document.addEventListener("focusin",e=>{if(e.target?.matches?.(".posSearch input"))schedule()},true);new MutationObserver(()=>schedule()).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener("load",schedule);setTimeout(schedule,100);setTimeout(schedule,500);window.addEventListener("storage",e=>{if(e.key===PRODUCTS_KEY)schedule()});

const summaryFix=document.createElement("style");summaryFix.textContent='.posView .summaryQty{display:none!important}.posView .posSummary{grid-template-columns:1fr 1fr!important}';document.head.appendChild(summaryFix);
