import React,{useEffect,useState} from "react";
import {Printer,RefreshCw,CheckCircle2,AlertCircle,Usb,Bluetooth,Wifi,FileText} from "lucide-react";
import "./printer-manager.css";
function connectionType(p){const s=`${p.name||""} ${p.displayName||""} ${p.description||""} ${p.portName||""}`.toLowerCase();if(s.includes("bluetooth"))return ["Bluetooth",Bluetooth];if(s.includes("wifi")||s.includes("network")||s.includes("\\\\"))return ["Wi‑Fi",Wifi];if(s.includes("usb"))return ["USB",Usb];return ["Windows",Printer]}
export default function PrinterManager(){
 const[printers,setPrinters]=useState([]),[selected,setSelected]=useState(""),[loading,setLoading]=useState(false),[printing,setPrinting]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const refresh=async()=>{setLoading(true);setError("");setMessage("");try{if(!window.desktopAPI?.getPrinters)throw new Error("واجهة الطباعة في Desktop غير متاحة");const list=await window.desktopAPI.getPrinters();setPrinters(Array.isArray(list)?list:[]);const saved=localStorage.getItem("bazaar_default_printer")||"";setSelected(list?.some(p=>p.name===saved)?saved:(list?.find(p=>p.isDefault)?.name||list?.[0]?.name||""));}catch(e){setError(e?.message||"تعذر قراءة طابعات Windows")}finally{setLoading(false)}};
 useEffect(()=>{refresh()},[]);
 const save=()=>{if(selected){localStorage.setItem("bazaar_default_printer",selected);setMessage("تم حفظ الطابعة الافتراضية")}};
 const test=async()=>{if(!selected)return;setPrinting(true);setError("");setMessage("");try{if(!window.desktopAPI?.printHtml)throw new Error("خدمة الطباعة في Desktop غير متاحة");const safe=selected.replace(/[&<>\"]/g,"");const html=`<div style="width:100%;max-width:760px;margin:0 auto;padding:28px;text-align:center;font-family:Arial,Tahoma,sans-serif"><h1 style="margin:0 0 8px;font-size:30px">كل شيء بالمعقول</h1><div style="font-size:18px">نقطة بيع</div><hr style="border:0;border-top:1px dashed #777;margin:20px 0"><h2 style="margin:10px 0">اختبار الطباعة ناجح</h2><p>تم إرسال هذا الوصل من برنامج بزار كل شيء بالمعقول.</p><p><b>الطابعة:</b> ${safe}</p><p><b>التاريخ:</b> ${new Date().toLocaleString("ar-DZ")}</p><hr style="border:0;border-top:1px dashed #777;margin:20px 0"><p>إذا خرج هذا الوصل من Epson L3110 فمسار الطباعة يعمل بشكل صحيح.</p><p style="margin-top:35px">شكراً لتجربتكم</p></div>`;const r=await window.desktopAPI.printHtml({html,silent:true,copies:1,deviceName:selected});if(!r?.ok)throw new Error(r?.error||"فشلت عملية الطباعة");setMessage("تم إرسال وصل الاختبار إلى الطابعة")}catch(e){setError(e?.message||"تعذرت الطباعة")}finally{setPrinting(false)}};
 return <div className="printerManager" dir="rtl"><div className="pmTitle"><div><h1><Printer/> مدير الطابعات</h1><p>إدارة الطابعات المثبتة في Windows واختبار الطباعة من البرنامج مباشرة.</p></div><button onClick={refresh} disabled={loading}>{loading?<RefreshCw className="spin"/>:<RefreshCw/>} تحديث</button></div><div className="pmCard"><div className="pmHead"><div><h2>الطابعات المتاحة</h2><span>{printers.length} طابعة مكتشفة</span></div><div className="pmStatus"><i/> Windows Desktop</div></div>{loading?<div className="pmEmpty"><RefreshCw className="spin"/><b>جاري اكتشاف الطابعات...</b></div>:printers.length===0?<div className="pmEmpty"><AlertCircle/><b>لم يتم العثور على طابعة</b><p>تأكد أن الطابعة مثبتة في Windows ثم اضغط تحديث.</p></div>:<div className="printerList">{printers.map((p,i)=>{const[t,Icon]=connectionType(p);return <button key={`${p.name}-${i}`} className={selected===p.name?"printerItem selected":"printerItem"} onClick={()=>setSelected(p.name)}><div className="printerIcon"><Icon/></div><div className="printerInfo"><strong>{p.displayName||p.name}</strong><small>{p.description||"طابعة Windows"}</small><span>{t}{p.portName?` · ${p.portName}`:""}</span></div><div className="printerState">{p.isDefault&&<em>افتراضية</em>}{selected===p.name&&<CheckCircle2/>}</div></button>})}</div>}<div className="pmActions"><button className="secondary" onClick={refresh} disabled={loading}><RefreshCw/> إعادة اكتشاف</button><button className="save" onClick={save} disabled={!selected}><CheckCircle2/> حفظ كافتراضية</button><button className="test" onClick={test} disabled={!selected||printing}>{printing?<RefreshCw className="spin"/>:<Printer/>}{printing?"جاري الطباعة...":"طباعة وصل اختبار"}</button></div>{message&&<div className="pmMessage success"><CheckCircle2/>{message}</div>}{error&&<div className="pmMessage error"><AlertCircle/>{error}</div>}</div><div className="pmNote"><FileText/><div><b>ملاحظة</b><p>طابعة Epson L3110 ستظهر هنا إذا كان تعريفها مثبتًا في Windows. سنستخدمها أولًا لاختبار مسار الطباعة الحقيقي، وبعد نجاحه نربط تصميم الوصل ونضيف دعم الطابعات الحرارية Bluetooth/ESC‑POS.</p></div></div></div>
}
